---
# logyard configuration.
# NOTE: configuration for non-logyard processes (eg: systail, apptail)
# also live here. thus it is by no means generic.

systail:
  max_record_size: 1024

apptail:
  max_record_size: 1024

# pre-configured drains. more can be added later via doozer.
drains:
  # Bounded storage for application logs, to be accessed from `s logs`.
  # max_records: how many log lines per app to keep?
  # heroku uses 1500; https://devcenter.heroku.com/articles/logging#log
  apptail: "redis://core/?filter=apptail&limit=1500"
  # Recent history of kato commands ran across the cluster
  kato_history: "redis://core/?filter=systail.kato&limit=256"
  # Recent logs from all nodes (WARNING: use only for dev/debug)
  systail: "redis://core/?filter=systail&limit=400"
  # Papertrail drain; note the query encoding.
  # papertrail: "udp://logs.papertrailapp.com:61282/?format=%7B%7B.Name%7D%7D%40%7B%7B.NodeID%7D%7D%3A+%7B%7B.Text%7D%7D"
  # Loggly
  # loggly: "tcp://logs.loggly.com:23452/"
