[>0;95;c] ---
# logyard configuration.
# NOTE: configuration for non-logyard processes (eg: systail, apptail)
# also live here. thus it is by no means generic.

systail:
  # this value should be large enough to _not_ make cloudevents trip
  # up on json unmarshall errors too often. 2048 should be good
  # enough.
  max_record_size: 2048

apptail:
  max_record_size: 950

# pre-configured drains. more can be added in doozer via logyardctl or
# 'kato drain'.
drains:
  # Bounded storage for application logs, to be accessed from `s logs`.
  # limit: how many log lines per app to keep? (XXX: must be a low
  # value until we move away from redis for app log buffer)
  # heroku uses 1500; https://devcenter.heroku.com/articles/logging#log
  builtin.apptail: "redis://core/?filter=apptail&limit=200"
  # Recent history of kato commands ran across the cluster stored as cloud events JSON
  builtin.katohistory: "redis://core/?filter=event.kato_action&limit=256&key=kato_history"
  # Recent cloud events from across the cluster
  builtin.cloudevents: "redis://core/?filter=event&limit=256&key=cloud_events"
