---
# logyard configuration.
# NOTE: configuration for non-logyard processes (eg: systail, apptail)
# also live here. thus it is by no means generic.

systail:
  # this value should be large enough to not make events trip up on
  # json unmarshall errors too often. 2048 should be good enough.
  max_record_size: 2048

apptail:
  max_record_size: 950

# pre-configured drains. more can be added later via doozer.
drains:
  # Bounded storage for application logs, to be accessed from `s logs`.
  # max_records: how many log lines per app to keep?
  # heroku uses 1500; https://devcenter.heroku.com/articles/logging#log
  apptail: "redis://core/?filter=apptail&limit=1500"
  # Recent history of kato commands ran across the cluster
  kato_history: "redis://core/?filter=systail.kato&limit=256&key=kato_history"
  # Recent cloud events from across the cluster
  cloud_events: "redis://core/?filter=event&limit=256&key=cloud_events"
  # Recent logs from all nodes (WARNING: use only for dev/debug)
  systail: "redis://core/?filter=systail&limit=400"
  # Papertrail drain; note the query encoding.
  # papertrail: "udp://logs.papertrailapp.com:61282/?format=%7B%7B.Name%7D%7D%40%7B%7B.NodeID%7D%7D%3A+%7B%7B.Text%7D%7D"
  # Loggly
  # loggly: "tcp://logs.loggly.com:23452/"
