---
# logyard configuration.
# NOTE: configuration for non-logyard processes (eg: systail, apptail)
# also live here. thus it is by no means generic.

systail:
  # this value should be large enough to not make events trip up on
  # json unmarshall errors too often. 2048 should be good enough.
  max_record_size: 2048

apptail:
  max_record_size: 950

# pre-configured drains. more can be added later via doozer.
drains:
  # Bounded storage for application logs, to be accessed from `s logs`.
  # max_records: how many log lines per app to keep?
  # heroku uses 1500; https://devcenter.heroku.com/articles/logging#log
  builtin_apptail: "redis://core/?filter=apptail&limit=1500"
  # Recent history of kato commands ran across the cluster
  builtin_katohistory: "redis://core/?filter=systail.kato&limit=256&key=kato_history"
  # Recent cloud events from across the cluster
  builtin_cloudevents: "redis://core/?filter=event&limit=256&key=cloud_events"
